Update pacstrap-docker

diff --git a/pacstrap-docker b/pacstrap-docker
--- a/pacstrap-docker
+++ b/pacstrap-docker
@@ -23,6 +23,9 @@ echo 'Creating /dev/null in new root'
 mknod "$newroot/dev/null" c 1 3
 
 echo 'Installing packages to %s' "$newroot"
+if ! pacman -r "$newroot" -Sy --noconfirm  archlinux-keyring; then
+	die 'Failed to install keyring to new root'
+fi
 if ! pacman -r "$newroot" -Sy --noconfirm "${pacman_args[@]}"; then
 	die 'Failed to install packages to new root'
 fi
